#:schema node_modules/wrangler/config-schema.json
name = "salla-case-study-billing-app"
account_id = "${CLOUDFLARE_WORKFLOW_ACCOUNT_ID}"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2024-10-11"

[env.dev]
kv_namespaces = [
    { binding = "CUSTOMER_KV", id = "${CUSTOMER_KV_ID}" },
    { binding = "SUBSCRIPTION_PLAN_KV", id = "${SUBSCRIPTION_PLAN_KV}" },
    { binding = "INVOICE_KV", id = "${INVOICE_KV_ID}" },
    { binding = "PAYMENT_KV", id = "${PAYMENT_KV_ID}" },
]

[env.dev.durable_objects]
bindings = [
    { name = "SIMPLE_DO", class_name = "SimpleDO" },
    { name = "BILLING_DO", class_name = "BillingCycle" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["SimpleDO"]


#[durable_objects]
#bindings = [
#    { name = "BILLING_CYCLE", class_name = "BillingCycle" }]


[build]
command = "npm install"

[env.production]
workers_dev = false

#[[kv_namespaces]]
#binding = "CUSTOMER_KV"
#id = "${CUSTOMER_KV_ID}"

#[[kv_namespaces]]
#binding = "SUBSCRIPTION_PLAN_KV"
#id = "${SUBSCRIPTION_KV_ID}"


#[[kv_namespaces]]
#binding = "INVOICE_KV"
#id = "${INVOICE_KV_ID}"


#[[kv_namespaces]]
#binding = "PAYMENT_KV"
#id = "${PAYMENT_KV_ID}"


#[[durable_objects.bindings]]
#name = "MyDurableObject"
#class_name = "MyDurableObject"


#[env.dev]


#watch = ["src/**/*.js", "src/**/*.ts"]
#ignore = ["node_modules/**"]
